Add CLI support for new Green LED APIs
home-assistant/cli pull request #423
Opened 2023-09-12 20:39 UTC by mdegat01

Add CLI support for the new APIs to set LEDs on Green added in https://github.com/home-assistant/supervisor/pull/4556

2023-09-13 06:49 UTC, pvizeli approved these changes

2023-09-19 08:25 UTC, agners requested changes

2023-09-19 08:25 UTC, agners commented on cmd/os_boards_green_options.go
> +	osBoardsGreenOptionsCmd.Flags().Bool("activity-led", true, "Enable/disable the activity LED")
```suggestion
	osBoardsGreenOptionsCmd.Flags().Bool("activity-led", true, "Enable/disable the green activity LED")
```

2023-09-19 08:25 UTC, agners commented on cmd/os_boards_green_options.go
> +	osBoardsGreenOptionsCmd.Flags().Bool("power-led", true, "Enable/disable the power LED")
```suggestion
	osBoardsGreenOptionsCmd.Flags().Bool("power-led", true, "Enable/disable the white power LED")
```

2023-09-19 08:25 UTC, agners commented on cmd/os_boards_green_options.go
> +	osBoardsGreenOptionsCmd.Flags().Bool("user-led", true, "Enable/disable the user LED")
We aligned on calling the LED by their function. For Yellow we defined this to be "system health" LED (see also https://green.home-assistant.io/documentation/interfaces/).

```suggestion
	osBoardsGreenOptionsCmd.Flags().Bool("system-health-led", true, "Enable/disable the yellow system health LED")
```

2023-09-19 08:25 UTC, agners commented on cmd/os_boards_green_options.go
> +	osBoardsGreenOptionsCmd.Flags().Lookup("user-led").NoOptDefVal = "true"
```suggestion
	osBoardsGreenOptionsCmd.Flags().Lookup("system-health-led").NoOptDefVal = "true"
```

2023-09-19 08:25 UTC, agners commented on cmd/os_boards_green_options.go
> +			"user-led",
```suggestion
			"system-health-led",
```

2023-09-29 08:53 UTC, agners approved these changes

2023-09-29 08:53 UTC, merged